### ISSUE TITLE
SvelteKit - TypeError: Cannot Read properties of undefined (reading: 'id")

### ISSUE THREAD

**Issue by ninicdennis** [vercel/speed-insights#27]
When including the new speed insights package into my application, Inside of the app, content stops loading and I see the following error 3 times in my console: 

```
TypeError: Cannot read properties of undefined (reading 'id')
    at injectSpeedInsights2 (@vercel_speed-insights_sveltekit.js?v=49aa9ded:88:41)
    at +layout.ts:5:1
```

The application does have analytics and speed insights both enabled.

**Comment by feugy** [comment]
Hello @ninicdennis, and thanks for the feedback. 
In order to help us fixing it as quickly as possible, could you share a minimal reproduction please?

**Comment by DanielRios549** [comment]
Same problem here. I just did what is said in the documentation, add the following code to `+layout.ts` file:

```js
import { injectSpeedInsights } from '@vercel/speed-insights/sveltekit'
injectSpeedInsights()
```

**Comment by DanielRios549** [comment]
@feugy Version 1.0.1 fix the error for me

**Comment by ninicdennis** [comment]
@feugy Verified on my end its working as intended! Thank you!
