### ISSUE TITLE
Required props for injectSpeedInsights

### ISSUE THREAD

**Issue by benoitrongeard** [vercel/speed-insights#32]
Hey,

Wanted to enable vercel speed insights with an Angular app.

I'm using Typescript@5.2.2 with Angular@17, vercel/speed-insights@1.0.1

The injectSpeedInsights function require a props argument.
To work well, and see vercel speed insight result and http calls in console, i set a empty object {} as props argument.

Without this argument, vercel speed insights don't work (Can't see http calls for insight inside network tab)

<img width="500" alt="Capture d’écran 2023-12-11 à 23 24 25" src="https://github.com/vercel/speed-insights/assets/5940350/6b312667-d36d-47b8-bdfb-f281f9c28771">

<img width="520" alt="Capture d’écran 2023-12-11 à 23 24 34" src="https://github.com/vercel/speed-insights/assets/5940350/c6440668-4760-4ef8-b77a-8e0256d8bb83">

**Comment by KingPr0o7** [comment]
Also had to do something like this, not sure what's the big deal. Now may I ask, @benoitrongeard do you receive any `VERCEL_ANALYTICS_ID not found` errors in your console?

**Comment by feugy** [comment]
Hello and thank you for the bug report.
The function needs an argument indeed, because it may needs to know the framework. The team is currently checking if we could make it optional or not.
More to come soon.

**Comment by feugy** [comment]
@benoitrongeard version 1.0.3 contains a fix and will be available within a few minutes.

**Comment by pifaace** [comment]
@benoitrongeard you're a GOAT
