### ISSUE TITLE
is Remix v2 supported ?

### ISSUE THREAD

**Issue by mzvdev** [vercel/speed-insights#39]
Hi 👋,

Is Remix v2 supported?
it's not very clear from the Readme file :)
But there is something in the source code.

**Comment by feugy** [comment]
Hello @mzvdev!

Yes, Remix is supported indeed. There's an [example app](https://github.com/vercel/speed-insights/tree/main/apps/remix), and you'll find all the install/usage instruction [here](https://vercel.com/docs/speed-insights/quickstart): just select "Remix" in the right-hand side combo-box.

I'll update our Readme accordingly.
