### ISSUE TITLE
Request for documentation to work with proxy CloudFlare

### ISSUE THREAD

**Issue by mzvdev** [vercel/speed-insights#40]
Hi,

is it possible to have a tutorial with screenshots about this stuff.
Didn't find where to fix 1. and 2. in CloudFlare dashboard.
```
[Not Working with Proxy](https://vercel.com/docs/speed-insights/quickstart#not-working-with-proxy)
Speed Insights may not function when using a proxy, such as [Cloudflare](https://vercel.com/docs/integrations/cloudflare).

How to fix:

1. Check your proxy configuration to make sure that all desired pages are correctly proxied to the deployment
2. Additionally, forward all requests to /_vercel/speed-insights/* to the deployments to ensure proper functioning of Speed Insights through the proxy
```

**Comment by feugy** [comment]
Hello @mzvdev. 

With a regular Cloudflare setup, you should have nothing to change, and Cloudflare should redirect all your traffic to Vercel.
This documentation paragraph is for more advanced cases where users already defined custom routing rules in the Cloudflare dashboard.

If you still don't receive any performance traffic from your Vercel project, please open a [support case](https://vercel.com/help#issues) so we could investigate it further.
