### ISSUE TITLE
`Cannot find package 'vite'` on Vercel build only 

### ISSUE THREAD

**Issue by LauraBeatris** [vercel/speed-insights#46]
### Description

Using Next.js 14.0.3 with Bun for dependencies management. 

Following the documentation: https://vercel.com/docs/speed-insights/quickstart, I've installed the package and rendered the component in the layout module. 

Running the build script on my local environment doesn't lead to compilation errors. However, when running the deployment on Vercel, getting the following error: 

![CleanShot 2024-01-20 at 19 00 30](https://github.com/vercel/speed-insights/assets/48022589/2f6b9f58-3490-40d0-8c6a-64a1fb5da7f7)

### Expected Behavior 

Would expect to be able to just install the package, render the component as guided, and get the deployment working leading to analytics insights on my Vercel dashboard. 

### Related issues

Took a look at a current open issue and saw some mentions around Vite, not sure if it's related, but flagging it for the maintainers: https://github.com/vercel/speed-insights/issues/44

**Comment by Icegreeen** [comment]
I believe the problem is due to the fact that this version of node is not compatible with Vite in the Vercel environment.

**Vite recommends node 18+ or 20+ (recommended)**

This version difference may be causing difficulty in finding the 'vite' package during the build and deploy process on Vercel

**Comment by huozhi** [comment]
Hi @LauraBeatris we had a fix in 1.0.6, can you try to upgrade to see if it resolves your issue? Thanks

**Comment by LauraBeatris** [comment]
@huozhi Working now with the latest package version, thank you for fixing it in such a timely manner!
