### ISSUE TITLE
Use process.env.ASSET_PREFIX when sending tracking data

### ISSUE THREAD

**Issue by officert** [vercel/speed-insights#63]
I'm using Vercel `speed-insights` and `analytics` with NextJS. However, our sites are behind a cloudflare proxy, where clients can point any path they want off their domain to our NextJS app. Ex:

https://foobar.com/shop -> proxy to our NextJS app

Our NextJS then rewrites the incoming urls to map them to the folder structure of our NextJS app.

When using `speed-insights` the request for the Javascript file always points to `https://foobar.com/_vercel/speed-insights/script.js`, which returns a 404 because we don't control that path on their domain.

I was able to get around this by using the HTML version, and our `process.env.ASSET_PATH` like this:

```js
<Script src={join(process.env.ASSET_PREFIX, '_vercel/speed-insights/script.js')} />
```

so that the script is served up from our Vercel provided domain name.

This works, however, all the tracking events are still pointing to `https://foobar.com/_vercel`.

Is it possible to have both the script tag and the tracking event use the `process.env.ASSET_PATH` if one is set? Or at least have a way to configure where `speed-insights` send the tracking events?

**Comment by officert** [comment]
@tobiaslins amazing thank you! I was able to switch this over, but now I'm getting a CORs error:

<img width="1185" alt="Screenshot 2024-03-25 at 9 48 42 AM" src="https://github.com/vercel/speed-insights/assets/4620560/c50c0b93-07c2-4e5a-92b5-af3fcd4f97e6">

**Comment by feugy** [comment]
I'm closing this ticket, feel free to re-open in case of need!
