### ISSUE TITLE
sample rate 

### ISSUE THREAD

**Issue by siyou** [vercel/speed-insights#64]
Why did I set the sample rate of SpeedInsights to 0.01, but it seems that the number of data points did not become one percent of the original?

**Comment by tobiaslins** [comment]
Hey! Did datapoints decrease or did nothing change at all for you?

**Comment by siyou** [comment]
Datapoints has decreased significantly.

**Comment by tobiaslins** [comment]
What is the issue then? I am not sure if I can follow

**Comment by siyou** [comment]
When I set the sampling rate to 0.01, I expected the number of data points to decrease to approximately 1% of the original quantity. However, it only decreased to 20% of the original quantity. After checking and calculating, I believe this may be due to the statistical reference data not covering the entire day or normal fluctuations. We can consider this matter resolved. Thank you for your assistance.
