### ISSUE TITLE
Getting Issue Uncaught SyntaxError: Unexpected token '<' (at script.js:1:1) with "@vercel/speed-insights": "^1.0.9" and "@vercel/speed-insights": "^1.0.12",

### ISSUE THREAD

**Issue by vantablanta** [vercel/speed-insights#76]
<img width="1140" alt="Screenshot 2024-08-28 at 07 00 51" src="https://github.com/user-attachments/assets/1d8f9d6b-6841-4a5e-9e4f-8dea2e5e1cbb">

We are getting data  as expected but I want to get rid of this error. 

How do I fix this ?

**Comment by thisismydesign** [comment]
How do you get rid of it?
